### ISSUE TITLE
Support TMUX and other terminals without hpa capability

### ISSUE THREAD

**Issue by ezh** [hchbaw/zce.zsh#3]
Please review my pull request hchbaw/zce.zsh#2

**Comment by hchbaw** [comment]
Thank you for your contribution.

The commit itself looks good to me, but I would like to be sure that you've contacted @lpm11 before merging.

It seems that I should merge https://github.com/lpm11/zce.zsh/commit/f2174f71c86b0c4b4f46b3e7bc512165c36d23a0, then #2.

**Comment by ezh** [comment]
1. Please explain the reason why I must contact @lpm11. He improve your code under the same license as the origin. I improve and publish changes under your license too. See ```COPYING```

2. Why you should merge lpm11@f2174f7 before #2?  You may just push **merge** button on #2. I fork your master branch, so my pull request have no any conflicts. My changes supersede @lpm11 solution.

**Comment by hchbaw** [comment]
Personally, I would like to respect someones' works as much as possible. The reason is not license issues, just my personal preferences.

Your #2 commit message refers just @lpm11, but I could not find the meaning at first sight. I presumed your patch is based on https://github.com/lpm11/zce.zsh/commit/f2174f7, so I wrote that I shoud merge it before yours.
I would at first contact him if I were you, though. Because it seems that he knows it better. 

If your patch were your original works, I would merge it just fine.
But it has references/parents, I would like to record them somehow, too if I can.

**Comment by lpm11** [comment]
Thank you for your kind consideration.

I'm fine either merging first lpm11@f2174f7 then #2, or directly #2. I'd like to follow an intention of project author, @hchbaw.

If I should make a PR of lpm11@f2174f7, please let me know.

**Comment by ezh** [comment]
Thank you all. I hope that this plugin will be only better.

**Comment by hchbaw** [comment]
Thank you for your contributions!

I've pushed the commits. I've merged both patches.
